/**
 * Featured images for the journal, taken from the legacy WordPress site.
 *
 * Every one of these already had a featured image on mikebastin.com, so
 * the rebuild had no reason to draw an abstract substitute for it
 * (owner, 20 Sep). `components/PostArt.tsx` stays as the fallback for a
 * post with no entry here, which is what a newly written post gets until
 * a picture is chosen for it.
 *
 * 57 entries: the 56 posts plus competitor-analysis-traffic-checklist,
 * which is a hand-built page rather than a post (HAND_BUILT_SLUGS in
 * lib/posts.ts) and is here because it is a cluster pillar the journal
 * index renders beside the others.
 *
 * All but one came from the legacy library. See the note on
 * conversational-ai-chatbots-business for the exception and why.
 *
 * `legacy` records where each file came from, relative to
 * https://mikebastin.com/wp-content/uploads/, so the set can be rebuilt
 * or re-checked against the source. The files in public/images/blog/
 * are webp derivatives: <slug>.webp at 1200px wide and
 * <slug>-thumb.webp at 160x84 for the footer, where a full-width image
 * would otherwise be shipped on every page of the site to be drawn at
 * 56px wide.
 *
 * `alt` describes the picture rather than repeating the post title,
 * which the heading beside it already carries. Roughly half the legacy
 * images had an empty alt attribute and the rest were thin, so these
 * were written from the images themselves.
 */

export type BlogImage = {
  width: number;
  height: number;
  alt: string;
  /**
   * Where the file came from, and what rebuilds it.
   *
   * A path under the legacy site's wp-content/uploads/ for the images
   * harvested from WordPress, which scripts/fetch-legacy-images.mjs
   * refetches. A "commons:File:..." title for the public domain
   * photographs, which scripts/fetch-commons-images.mjs rebuilds. An
   * "unsplash:<id>" reference for the one photo from there, which has no
   * script behind it and was downloaded once. An "owner:<file>" reference
   * for a picture the owner supplied directly, which likewise has no
   * script behind it: the committed webp is the only copy, so
   * fetch-legacy-images.mjs skips these the way it skips the other two.
   */
  legacy: string;
  /**
   * Which part of the frame to keep when cropping to 1200x630.
   *
   * Only the `commons:` photographs are cropped rather than scaled, and
   * sharp's `attention` strategy, which keeps whatever it scores as most
   * interesting, decapitated two of them: it preferred a tabulating
   * machine to the woman operating it, and a desk of paperwork to the two
   * men standing over it. "top" keeps heads, which is what an archival
   * photograph of people needs; "attention" is right where the subject is
   * the object.
   */
  cropFocus?: "top" | "centre" | "attention";
  /**
   * Where a photo came from, when it is not from the legacy library.
   *
   * Recorded, not rendered. Nothing on this site carries a credit line,
   * which is the owner's decision and is why every sourced photo here is
   * either public domain, CC0, or under the Unsplash License: all three
   * owe no attribution. A photo that required one would have to be
   * credited on the page, so it does not get used.
   *
   * Recording it anyway means a file can always be traced back to who
   * made it and on what terms, which is the part that matters to whoever
   * inherits this. `licence` is what the source itself states, so a
   * future audit reads this rather than trusting the choice made here.
   */
  credit?: { author: string; source: string; sourceUrl: string; licence: string };
};

export const BLOG_IMAGES: Record<string, BlogImage> = {
  "15-simple-blog-post-ideas-to-help-attract-more-customers-to-your-business": { width: 1200, height: 494, alt: "Hands typing on a laptop beside an open notebook and a second keyboard", legacy: "2024/10/Simple-Blog-Post-Ideas.jpg" },
  "360-marketing-agency": { width: 1200, height: 529, alt: "A man facing a tunnel of screens showing many different images at once", legacy: "2024/12/360-Marketing-Agency.jpg" },
  // Sixteen heroes regenerated on 23 Sep 2026 with the owner's BlogIllustrator
  // tool, replacing legacy stock that showed the letters SEO glowing over a
  // laptop, icons floating above a keyboard, or a product logo. Prompts and
  // settings are in docs/BRANDED-IMAGE-PROMPTS.md. Four were generated twice:
  // the first pass put FUJIFILM, KUKA and Deutsche Bahn marks into three
  // frames and pasted flat sticker flags onto the harbour ships, so the
  // shipped versions are the second pass, checked at full size for lettering.
  "affiliate-marketing-programs": { width: 1200, height: 630, alt: "Two relay runners passing the baton on a coastal running track at sunset", legacy: "owner:blog-illustrator/affiliate-marketing-programs.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "ai-powered-marketing": { width: 1200, height: 630, alt: "The great glass lens of a lighthouse throwing beams of light across a dark sea", legacy: "owner:blog-illustrator/ai-powered-marketing.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  // Replaced the 1950 census tabulating-machine photograph on 22 Sep 2026,
  // on an image supplied by the owner. Cropped bottom-anchored rather than
  // by attention, which cut the compass and the shield in half.
  "alternatives-to-google-analytics": { width: 1200, height: 630, alt: "A laptop on a wooden desk showing a dashboard of charts, beside a brass compass, a frosted glass shield and a cup of coffee", legacy: "owner:2026-09-22-analytics-desk.jpg", credit: { author: "Supplied by the owner", source: "Owner", sourceUrl: "", licence: "Owner-supplied, no attribution required" } },
  "best-practices-for-multilingual-seo": { width: 1200, height: 630, alt: "Cargo ships with different coloured hulls guided into separate berths in a harbour at golden hour", legacy: "owner:blog-illustrator/best-practices-for-multilingual-seo.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "best-vietnam-sourcing-agencies-for-eudr-supplier-scouting-and-audits": { width: 1200, height: 764, alt: "Weathered timber planks in several colours, laid side by side", legacy: "2025/12/vietnam-sourcing-agencies.jpg" },
  "building-a-global-brand": { width: 1200, height: 800, alt: "A globe resting on a dark surface lit by circuit lines", legacy: "2024/09/Building-a-Global-Brand-1.jpg" },
  "chrome-extensions-for-seo": { width: 1200, height: 630, alt: "A canvas tool roll opened on a workbench, each precision tool in its own slot", legacy: "owner:blog-illustrator/chrome-extensions-for-seo.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "chrome-extensions-for-translators": { width: 1200, height: 630, alt: "A row of camera lenses of different lengths on a navy cloth beside a camera body", legacy: "owner:blog-illustrator/chrome-extensions-for-translators.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "common-mistakes-to-avoid-when-localising-your-website": { width: 1200, height: 705, alt: "A hand writing the words common mistakes on a notepad", legacy: "2024/09/common-mistakes-to-avoid-when-cocalizing-your-website.jpg" },
  "competitor-analysis": { width: 1200, height: 630, alt: "A man reading at a subway magazine stand, its racks filled with competing titles", legacy: "commons:File:MAGAZINE STAND IS LOCATED ONLY A FEW STEPS AWAY FROM A PLATFORM ON THE LEXINGTON AVENUE LINE OF THE SUBWAY. IN 1970... - NARA - 556675.jpg", credit: { author: "Jim Pickerell", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:MAGAZINE_STAND_IS_LOCATED_ONLY_A_FEW_STEPS_AWAY_FROM_A_PLATFORM_ON_THE_LEXINGTON_AVENUE_LINE_OF_THE_SUBWAY._IN_1970..._-_NARA_-_556675.jpg", licence: "Public domain" } },
  "competitor-analysis-traffic-checklist": { width: 1200, height: 686, alt: "A fountain pen resting on a printed checklist, with reading glasses and a monitor showing a traffic dashboard behind", legacy: "2026/01/competitoranalysistrafficcheck.jpg" },
  "content-optimisation-for-spanish-users": { width: 1200, height: 482, alt: "A woman smiling at an outdoor cafe table on a Spanish street", legacy: "2024/10/spanish-users.jpg" },
  // The only entry here not from the legacy library. Its WordPress image
  // was an AI mockup reading "Hello! How can bo help?" beside "Hola!
  // /Como pudo ayodrarte", and every other candidate in that batch was
  // no better, so this is a real photograph from Unsplash instead.
  "conversational-ai-chatbots-business": { width: 1200, height: 800, alt: "A woman holding a phone in both hands, part-way through typing a message", legacy: "unsplash:HbyYFFokvm0", credit: { author: "Paul Hanaoka", source: "Unsplash", sourceUrl: "https://unsplash.com/photos/HbyYFFokvm0", licence: "Unsplash License" } },
  "digital-marketing-advisor": { cropFocus: "centre", width: 1200, height: 630, alt: "An art director and a copy writer working together at an advertising agency in Detroit, 1942", legacy: "commons:File:Art director and copy writer at a large advertising agency. Detroit, Michigan. July 1942. (26767552717).jpg", credit: { author: "Britt Fuller from Tallahassee, United States of America", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Art_director_and_copy_writer_at_a_large_advertising_agency._Detroit,_Michigan._July_1942._(26767552717).jpg", licence: "Public domain" } },
  "eeat-vs-aeat-typo": { width: 1200, height: 666, alt: "A cover graphic reading EEAT versus AEAT, the typo that turns an SEO audit into a tax audit", legacy: "2026/01/EEAT-AEAT-1.jpg" },
  "email-marketing-hacks-boosting-open-rates-and-conversions": { width: 1200, height: 489, alt: "A laptop showing one unread email in an inbox, next to a cup of coffee", legacy: "2024/11/Email-Marketing-Hacks.jpg" },
  "english-to-french-translation-services": { width: 1200, height: 672, alt: "A ball painted in the French flag resting on a laptop keyboard", legacy: "2024/09/english-to-french-translation-services.jpg" },
  "french-ppc-campaign": { width: 1200, height: 563, alt: "A hand reaching towards a laptop screen showing a bar chart", legacy: "2024/09/French-PPC-Campaign.jpg" },
  "future-of-seo": { width: 1200, height: 630, alt: "An observatory dome open at dusk on a rocky coastline, its telescope angled at the sky", legacy: "owner:blog-illustrator/future-of-seo.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "german-seo-best-practices": { width: 1200, height: 630, alt: "A white high-speed train arriving at a modern station platform at blue hour", legacy: "owner:blog-illustrator/german-seo-best-practices.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "german-seo-content-localisation": { width: 1200, height: 426, alt: "A man at a whiteboard diagram with SEO at the centre, branching to keywords, pages, links, content and media", legacy: "2024/09/german-seo-content-localization.jpg" },
  "global-business-trends": { width: 1200, height: 644, alt: "Five colleagues around a meeting table, each working on a laptop or tablet", legacy: "2020/04/agency-post-02.jpg" },
  "google-analytics-international-marketing-limits": { width: 1200, height: 686, alt: "Two monitors on a desk showing analytics dashboards and a world map", legacy: "2026/01/googleanalyticsinternationalma.jpg" },
  "how-ai-is-revolutionising-seo-strategies": { cropFocus: "top", width: 1200, height: 630, alt: "A computer operator at an IBM 4381 work station in a mainframe room", legacy: "commons:File:A computer operator works at an IBM 4381 four-window work station in a computer room at the Arnold Engineering Development Center, where numerous mainframe and super computers are u - DPLA - b8ef28c4e9b101b7ccc7f2e5ee1a68ed.jpeg", credit: { author: "Department of Defense. American Forces Information Service. Defense Visual Information Center. 1994", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:A_computer_operator_works_at_an_IBM_4381_four-window_work_station_in_a_computer_room_at_the_Arnold_Engineering_Development_Center,_where_numerous_mainframe_and_super_computers_are_u_-_DPLA_-_b8ef28c4e9b101b7ccc7f2e5ee1a68ed.jpeg", licence: "Public domain" } },
  "how-ai-is-transforming-translation-and-localisation": { width: 1200, height: 630, alt: "A robotic arm and a craftsperson working together on a blue and cream mosaic", legacy: "owner:blog-illustrator/how-ai-is-transforming-translation-and-localisation.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "how-to-create-a-targeted-content-strategy": { width: 1200, height: 630, alt: "An archer at full draw aiming at a target across a misty lake at sunrise", legacy: "owner:blog-illustrator/how-to-create-a-targeted-content-strategy.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "how-to-promote-your-local-business-on-google-maps": { width: 1200, height: 673, alt: "A hand holding a phone that shows a map with a red location pin", legacy: "2020/11/google-maps-marketing.jpg" },
  "how-to-use-ai-and-machine-translation-tools": { width: 1200, height: 630, alt: "Hands finishing the rim of a dark ceramic bowl on a potter's wheel", legacy: "owner:blog-illustrator/how-to-use-ai-and-machine-translation-tools.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "how-to-write-about-your-professional-background": { width: 1200, height: 644, alt: "Colleagues talking around a desktop monitor in a studio", legacy: "2020/04/agency-post-04.jpg" },
  "human-creator-economy": { width: 1200, height: 800, alt: "A creator speaking into a microphone in front of a camera", legacy: "2025/11/Human-Creator-Economy.jpg" },
  "internal-linking-tools": { width: 1200, height: 630, alt: "Old stone bridges linking a chain of small islands across a calm bay, seen from above", legacy: "owner:blog-illustrator/internal-linking-tools.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "law-firm-seo-services": { width: 1200, height: 512, alt: "Two people in business suits walking outside a glass office building", legacy: "2024/12/law-firm-SEO.jpg" },
  "link-building-in-spain": { width: 1200, height: 431, alt: "A wooden bobbin resting on a pillow of handmade Spanish lace", legacy: "2024/10/spanish-link-building.jpg" },
  "link-selling-and-link-buying-platforms": { width: 1200, height: 483, alt: "Chain links in several bright colours, joined in a row", legacy: "2024/12/Link-Selling-and-Link-Buying-Platforms.jpg" },
  "llms-beyond-giants-hidden-ai-models": { width: 1200, height: 630, alt: "Two women setting the switches on the ENIAC computer by hand", legacy: "commons:File:Two women operating ENIAC (full resolution).jpg", credit: { author: "Unidentified U.S. Army photographer", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Two_women_operating_ENIAC_(full_resolution).jpg", licence: "Public domain" } },
  "localisation-testing-tools": { width: 1200, height: 630, alt: "An inspector checking rows of ceramic plates glazed in different regional patterns", legacy: "owner:blog-illustrator/localisation-testing-tools.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "mastering-the-art-of-networking": { width: 1200, height: 900, alt: "A city skyline with portrait photographs joined by a network of lines", legacy: "2024/09/ai-generated-internet-technology-8259052.jpg" },
  "most-popular-marketing-strategies": { width: 1200, height: 644, alt: "Four colleagues at a white table, looking at phones and a tablet", legacy: "2020/04/agency-post-01.jpg" },
  "optimising-multilingual-website-content": { width: 1200, height: 430, alt: "Hands typing on a laptop with a faint data overlay across the desk", legacy: "2024/10/optimising-multilingual-website-content.jpg" },
  "optimising-your-website-for-valencia-based-searches": { width: 1200, height: 504, alt: "Two women at a market stall, with a search box drawn across the photograph", legacy: "2025/01/local-seo-valencia.jpg" },
  "search-everywhere-strategy": { width: 1200, height: 630, alt: "An open library card catalogue drawer, its cards raised part-way through a search", legacy: "commons:File:Copyright Card Catalog Drawer.jpg", credit: { author: "Michael Holley Swtpc6800", source: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Copyright_Card_Catalog_Drawer.jpg", licence: "Public domain" } },
  "seo-in-belgium": { width: 600, height: 338, alt: "A computer keyboard with one key carrying the Belgian flag and another a tick", legacy: "2024/10/Belgium-SEO-1.jpg" },
  "spanish-keyword-localisation": { width: 1200, height: 475, alt: "A search box graphic on a yellow background, filled with keyword tags", legacy: "2024/10/spanish-keyword-research.jpg" },
  "spanish-on-page-seo": { width: 1200, height: 509, alt: "A red Spanish hair comb and fan set against roses", legacy: "2024/10/Spanish-On-Page-SEO.jpg" },
  "spanish-seo-markets": { width: 1200, height: 800, alt: "Hands typing on a laptop with a search field open on screen", legacy: "2024/10/spanish-seo.jpg" },
  "technical-seo-audit-checklist": { width: 1200, height: 630, alt: "An engineer at dusk checking the bolted joints of a steel building frame with a torch, the sea behind", legacy: "owner:blog-illustrator/technical-seo-audit-checklist.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "technical-seo-considerations-for-german-websites": { width: 1200, height: 630, alt: "Close detail of bolts on a steel bridge above a German river valley", legacy: "owner:blog-illustrator/technical-seo-considerations-for-german-websites.png", credit: { author: "Generated by the owner with BlogIllustrator AI", source: "Owner", sourceUrl: "", licence: "Owner-generated, no attribution required" } },
  "technical-seo-for-multilingual-websites": { width: 1200, height: 535, alt: "Four people holding a blank banner beside globe icons on a brick wall", legacy: "2024/12/Technical-SEO-for-Multilingual-Websites.jpg" },
  "technical-seo-for-spanish-search-engines": { width: 1200, height: 800, alt: "A view across the rooftops of Barcelona towards the Sagrada Familia", legacy: "2024/10/cathedral-sagrada-familia-barcelona-427997.jpg" },
  "user-interface-localisation-can-transform-your-global-reach": { width: 1200, height: 577, alt: "A phone on a desk showing a wireframe layout of a mobile interface", legacy: "2024/10/User-Interface-Localisation.jpg" },
  "what-is-search-intent-mapping": { width: 1200, height: 428, alt: "A man pointing at an empty search box outlined in red", legacy: "2024/10/search-intent-mapping.jpg" },
};

export function getBlogImage(slug: string): BlogImage | undefined {
  return BLOG_IMAGES[slug];
}
